spring:
  application:
    name: authserver

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/USERSERVICE?autoreconnect=true&serverTimezone=UTC"
    password: "Sree@8606"
    username: "root"

config:
  oauth2:
    clientid: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzEyODU4NzIsImV4cCI6MTYzMTI5MzA3MiwidXNlcklkIjo1MSwiY2xpZW50SWQiOiJnaW9sb2ZyaGwiLCJyZXNvdXJjZVNlcnZlcklkIjoic2RoZCIsIm1ldGFkYXRhIjoiQWdlbnQgTUFDSUQ6IDEyMjMsIEFwcCB0eXBlOiBzZW5zaXRpdmUsIHNpZ25hdHVyZSBhbGdtOiBTSEEifQ.1Qwol-8lt7-ZEmTnZnInFqnxbEW_-fCxJBND2rA8nl0
    clientSecret: sree@123
    privateKey: -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAr05j4NTfyQj1LVn8JATu1Zvr3LNs90nktjSg3jMOPa5R49oY
      RLquu7ijt9EHNmSfTVNrjeByHnI0hXc5RazGuhId1OjbuRx/3i9YMkzO2C2SYizl
      wrvFJoIZq0SVcnSaSYN0MQ3Nc6BcIqD4woaUZrHD8WTCdm5rHjPEEa9A/FIDLR/V
      19bAcOZX9nZHwI39KFL44Y2W2lariyMdybANZ7sa5nToutHGfFrzWrONBO1fltp3
      AI6pMIyrFY4Q37aF6M5Am0GKehG+3vFgrhd+f9rOWxGbTnuFahuysXEUiWixsqOW
      H5G8MqoAeutB69qpRASd3Of9IEWgcA0Id6pp8wIDAQABAoIBAQCd1LnfpkiEuufi
      mO2FkFtnPiYwYeptCb48vU1IQDdGGTfpKGZJGrpOkIH18N/JfPZfrAddiQG1n6Th
      tOF/dXrF86GgGrYYByyoYX/KaZSg1QbCFSIXHO73KJLru6fBkHGIVi26LG8Y9vt8
      wei1Wm0puEptfwYFkowmePzB30Nm5wBsWJ0CWCW9Rzq2QODFxxojcuawUTJRKKb2
      woC90ifeegTLl7iNPAGyKsNzqqDDTiQa9hLrbSHm2cMzwiZQMln5xipSBlZR3t/S
      LHbsogTkgIwNeeEhBuL5nQLjrb8pf5a/BPSlTlu5zMmaGz2WAOggjfnx45O68hwm
      nFCzZAihAoGBAOll0jj0rpPMhzPSxPukJ/yVzGkDwQ5y3wBNoUX9RCk0cRGCJKaU
      ePG7khL9R4QDqCF4djm0ZKvvElPdyb9eqF1uueS9OPirBrNBbRGgwDXqvkn49335
      Gtj9CYhq9YfGqzOx+qdSW9hj6W26PC/6zYbQLC4JMVMIW4wiq5L2KepFAoGBAMBI
      awX1IaYMvStV0JwJENfCoOWwZj/0iAiuShWUfeppHY9CatzUHiRVIZHOiAJZhi/L
      18d8pynSpuGmbqnmKUYwCySgVZ+JFLjUHRhlsJ6DJJoetIIvzfTYZJA202wIbMqh
      PqdcD9OQGW6kaMjfaHaiVGiJ4TqGron/xKlqS6LXAoGBAM0f3diMwvnGoXTcYp8+
      sJ3/EX2h/QQz1OWxVHHsmwETw+O9W3TDvF/HmCP0UewmQpfYBR/F+UxaeuMWY387
      NAGZlOsBmpaByQu2DqOVghhgzQi6NNmUGxJloQEx78R6yHBQlZiEe4/8j2UObmNE
      q2k2f/2duqndCIhq2Bv7GO95AoGAArwE6ZzG0bm0pv0dblqipq7Z4upTSe2MUbNI
      0m2+LKs6BGOJaYKKuzGKvKwXOxFS2zMm6mtXZTzdqq/XOwtO4vSj8+1jylUEumwp
      zcMEc/yhdJ+jKYbMgwLgyzw8XXjxMyB/55ljkDqoYe5snw6uSaGdWa88SLzJlqTQ
      gyhD0xkCgYBwfTW1Vm6xlBD5YD24hZHhyLYV9PQk96N7fzuYLLCz48jogO1PjW4N
      0x2FD8T0KpuvHynyt+gwrk4l8e49zLIMIS6x9x6Z08Qrb1EzG+4r2X6YY3NDkplr
      1Ry4dljjW0nw/IZq6/0zdKl6x6AGF4hIKBP1+x/tZVTrY7j+fsY/Tw==
      -----END RSA PRIVATE KEY-----

    publicKey: -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr05j4NTfyQj1LVn8JATu
      1Zvr3LNs90nktjSg3jMOPa5R49oYRLquu7ijt9EHNmSfTVNrjeByHnI0hXc5RazG
      uhId1OjbuRx/3i9YMkzO2C2SYizlwrvFJoIZq0SVcnSaSYN0MQ3Nc6BcIqD4woaU
      ZrHD8WTCdm5rHjPEEa9A/FIDLR/V19bAcOZX9nZHwI39KFL44Y2W2lariyMdybAN
      Z7sa5nToutHGfFrzWrONBO1fltp3AI6pMIyrFY4Q37aF6M5Am0GKehG+3vFgrhd+
      f9rOWxGbTnuFahuysXEUiWixsqOWH5G8MqoAeutB69qpRASd3Of9IEWgcA0Id6pp
      8wIDAQAB
      -----END PUBLIC KEY-----
server:
  port: 8081

#management:
#  endpoints:
    #web:
      #exposure:
        #include: "*"




